name: Deploy site

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
          
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          directory: ./
